spring:
  application:
    name: zaldo-api

  # Configuração de Banco de Dados
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/zaldo}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # JSON Pretty Print (Útil para debugar respostas no Postman/Bruno)
  jackson:
    serialization:
      indent_output: true

  # Docker Compose Support
  # Isso garante que o Spring leia o docker-compose.yml na raiz e suba o banco sozinho
  docker:
    compose:
      enabled: false
      file: ./compose.yml
      lifecycle-management: start-only # Inicia o banco ao rodar a app, mas não derruba ao parar

# Configurações Customizadas da Aplicação
api:
  security:
    token:
      # Defina um segredo padrão longo para dev, sobrescreva em prod
      secret: ${TOKEN_JWT:345345fsdf345345sdfsdf345345sdfsdfgsdfg345345}
      bot: ${TOKEN_TELEGRAM_BOT}