services:
  postgres:
    image: docker.io/postgres:18.1-alpine
    container_name: zaldo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zaldo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
  redis:
    image: docker.io/redis:8.4-alpine
    container_name: zaldo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data:Z
volumes:
  postgres_data:
  redis_data:
